### ISSUE TITLE
Enable TextWrap in ForumsPostsPage

### ISSUE THREAD

**Issue by agangal** [agangal/TeamSnapV2#10]

**Comment by Starlon99** [comment]
![drawing_165714](https://cloud.githubusercontent.com/assets/16710262/12338871/a75169ec-bad7-11e5-9712-18f78ec8a88b.jpg)

**Comment by agangal** [comment]
Thanks! Definitely text wrapping. I'll put this fix in the Monday release.

**Comment by agangal** [comment]
Fixed long ago :P
